apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp-deployment
  labels:
    app: nodejs_demo_image
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs_demo_image
  template:
    metadata:
      labels:
        app: nodejs_demo_image
    spec:
      containers:
      - name: nodeserver
        image: 295134731113.dkr.ecr.eu-north-1.amazonaws.com/nodewebapp:nodejs_demo_image
        ports:
        - containerPort: 3000
