name: ci

on:
  push:
    branches:
      - "main"

jobs:        
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.23.6'
        id: install
      -
        name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1
      -
        name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1
       
      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: 295134731113.dkr.ecr.eu-north-1.amazonaws.com
          ECR_REPOSITORY: nodewebapp
          IMAGE_TAG: nodev1
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG . --file ./Dockerfile
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Update kube config
        run: aws eks update-kubeconfig --name nodewebapp --region eu-north-1

      - name: Deploy image to Amazon EKS
        run: |
          kubectl apply -f eks/deployment.yml
          kubectl apply -f eks/deploymentservice.yml
